Wywolanie nr 10. Program spal juz przez 1 sekund
Wywolanie nr 9. Program spal juz przez 2 sekund
Wywolanie nr 8. Program spal juz przez 3 sekund
Wywolanie nr 7. Program spal juz przez 4 sekund
Wywolanie nr 6. Program spal juz przez 5 sekund
Wywolanie nr 5. Program spal juz przez 6 sekund
Wywolanie nr 4. Program spal juz przez 7 sekund
Wywolanie nr 3. Program spal juz przez 8 sekund
Wywolanie nr 2. Program spal juz przez 9 sekund
Wywolanie nr 1. Program spal juz przez 10 sekund
